services:
  db:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secure
      - MYSQL_DATABASE=learn-srs
    volumes:
      - mysqldata:/var/lib/mysql
    restart: unless-stopped
  
volumes:
  mysqldata: